### ISSUE TITLE
Support installation on VMs running in a cloud provider (where mDNS does not work)

### ISSUE THREAD

**Issue by jiridanek** [canonical/microcloud#134]
The documentation warns that mDNS will fail on a cloud provider

> MicroCloud uses mDNS to automatically detect other servers on the network.
> This method works in physical networks, but it is usually not supported in a cloud environment.
> https://canonical-microcloud.readthedocs-hosted.com/en/latest/explanation/initialisation/#explanation-initialisation

Is it possible to specify cluster node addresses by hand? According to https://github.com/canonical/microcloud/issues/35 this feature was considered. It does not seem to be implemented, though. Not in microcloud 0.1.

```
ubuntu@djobik:~$ sudo microcloud init
Select an address for MicroCloud's internal traffic:

 Using address "10.0.169.48" for MicroCloud

Limit search for other MicroCloud servers to 10.0.169.48/24? (yes/no) [default=yes]: 
Scanning for eligible servers ...
```

Microovn also seems to rely on mDNS, so joining nodes on a cloud provider there does not seem to work either.

**Comment by masnax** [comment]
For now, MicroCloud requires mDNS communication in order to have some semblance of restriction to access for the APIs of its services (currently LXD, MicroCeph, MicroOVN). Otherwise, MicroCloud would expose those services' APIs to whomever is on the network. 

With the upcoming preseed file support, you should be able to specify beforehand what your cluster ought to look like, but the machines would still need to be able to communicate over mDNS.

Once we have preseed support in place, we can look into having each daemon spit out an auth token that can be used to bypass mDNS if the token is included in the preseed file.

**Comment by jiridanek** [comment]
Thanks. In general, I'd feel better with using either preseed, or join tokens. The scanning of network and accepting whatever is there feels flimsy, albeit convenient for a quickstart, of course!

**Comment by roosterfish** [comment]
Preseed support is now available. See the latest docs: https://canonical-microcloud.readthedocs-hosted.com/en/latest/how-to/initialise/#non-interactive-configuration

**Comment by masnax** [comment]
Pressed support is available, but still requires multicast for now. So reopening this.

**Comment by roosterfish** [comment]
@masnax thanks for the clarification.

**Comment by respadas** [comment]
Hey guys, is this feature availble now or not yet? I´m trying to use in AWS without success even enabling multicast throutgh transit gateway.

My stack is microcloud 1.1-04a1c49 and always get stuck in "Scanning for eligible servers ..."

Or exist any workaround?

**Comment by roosterfish** [comment]
@respadas I have accidentally closed the issue, but multicast support is still required in order to bootstrap MicroCloud.

**Comment by hayone1** [comment]
It's actually possible to bootstrap microcloud in the public cloud with fairly good performance using tunnelling(vxlan).
I've been able to run it on Azure at least.

It's also possible to bootstrap in a basic network (ipip tunnel).
I've just started a project that automates this configuration. You can check it out at [microcloud-automated](https://github.com/hayone1/microcloud-automated) and hopefully contribute to it too.

**Comment by roosterfish** [comment]
https://github.com/canonical/microcloud/pull/383 added support for unicast to form MicroClouds which doesn't anymore require multicast to be available on the network.
