### ISSUE TITLE
Handle MicroCeph already installed

### ISSUE THREAD

**Issue by escabo** [canonical/microcloud#145]
I have MicroCeph installed independently, before MicroCloud to use a dedicated network. When asked during the MicroCloud install if I want distributed storage, I say "no", but there seems to be an internal assumption preventing the setup to complete.

```
Would you like to set up distributed storage? (yes/no) [default=yes]: no

Configure distributed networking? (yes/no) [default=yes]: 
Select exactly one network interface from each cluster member:

 Using "enp6s0" on "n2" for OVN uplink
 Using "enp6s0" on "n1" for OVN uplink
 Using "enp6s0" on "n3" for OVN uplink

Specify the IPv4 gateway (CIDR) on the uplink network (empty to skip IPv4): 192.168.10.1/24
Specify the first IPv4 address in the range to use with LXD: 192.168.10.100
Specify the last IPv4 address in the range to use with LXD: 192.168.10.200
Specify the IPv6 gateway (CIDR) on the uplink network (empty to skip IPv6): 
Initializing a new cluster
 Local MicroCloud is ready
 Local LXD is ready
 Local MicroOVN is ready
Error: Failed to bootstrap local MicroCeph: Failed to initialize local remote entry: A remote with name "n1" already exists
```

**Comment by escabo** [comment]
This could also be solved by allowing the user to choose a different network for Ceph during the installation of MicroCloud.

**Comment by masnax** [comment]
Good point! We can definitely try to check if we are already clustered with microceph/ovn on all the same systems (probably by hostname) and if so we can prompt the user if they want to use the existing services to setup devices for LXD, and potentially add new disks/network interface.

**Comment by tregubovav-dev** [comment]
We need to check whether microceph, microovn and/or lxd are already clustered.

I investigate ways to migrate existing lxd cluster to microcloud and see it's not possible now.
Example below:

Initializing a new cluster
 Local MicroCloud is ready
 Local MicroOVN is ready
 Local MicroCeph is ready
Error: Failed to bootstrap local LXD: This LXD server is already clustered
