### ISSUE TITLE
Different `core.https_address` on init member

### ISSUE THREAD

**Issue by roosterfish** [canonical/microcloud#214]
When deploying a new MicroCloud cluster, the node on which `microcloud init` gets executed has a different setting for `core.https_address` compared to its cluster peers. It is using the wildcard pattern `[::]:8443` unlike its peers which use the primary IP of the machine `{IP}:8443`.  

```bash
julian@thinkpad:~$ lxc exec m1 -- lxc config get core.https_address
[::]:8443
julian@thinkpad:~$ lxc exec m2 -- lxc config get core.https_address
10.146.93.224:8443
julian@thinkpad:~$ lxc exec m3 -- lxc config get core.https_address
10.146.93.54:8443

```

**Comment by masnax** [comment]
Looks like this was intentional, although I'm not sure of the reason: https://github.com/canonical/microcloud/commit/f5c9812

**Comment by tomponline** [comment]
In my view it should end up the same style of configuration on each member.
So either set to an individual node address or a wild card address on all members.

**Comment by roosterfish** [comment]
I guess since we already use `[::]:8443` for one of the nodes we should continue using the wildcard.
