### ISSUE TITLE
README.md could be more specific :)

### ISSUE THREAD

**Issue by camglegg** [canonical/microcloud#22]
I would love to help if possible. Even if it is just adding:

```
snap install microcloud
```

This seems like a very cool project!

**Comment by stgraber** [comment]
Ah yeah, there's definitely the need for a proper README around here ;)

We'd love to have you contribute, just note that this project falls under the Canonical CLA and that contributors need to sign or have previously signed it at: https://ubuntu.com/legal/contributors/agreement

**Comment by camglegg** [comment]
Awesome! I just signed the Agreement.

I will clone the repo and get to work. Is there any other documentation that I can pull from?

**Comment by camglegg** [comment]
Watched [the video](https://youtu.be/ZSZoLnp-Ip0).

Read [the post](https://discuss.linuxcontainers.org/t/introducing-microcloud/15871).

Much appreciated. I will test it tonight and hopefully get something together for the README.

**Comment by camglegg** [comment]
@stgraber  README.md is done. Sorry this is going to sound stupid but...

What is process to create a PR for this repo? I obviously don't have auth credentials. I have only ever worked with repo's I have owned.

**Comment by tomponline** [comment]
You clone the repo into your account, make the commits there and then open a pull request from your clone back to the source one.

**Comment by camglegg** [comment]
That is awesome thank you @tomponline !

**Comment by camglegg** [comment]
Added to Pull Request #24
