### ISSUE TITLE
microcloud snap-: apparmor denial while reading ssl certificate

### ISSUE THREAD

**Issue by prash813** [canonical/microcloud#225]
I have been playing with microcloud setup for a while now.
I have three arm64 boards all with ubuntu core 22 images
2 Xilinx KV260 and a Mediatek board.

While the setup works fine . But even under working microcloud setup, I see following apparmor denial message

`
729:[ 1062.382278] audit: type=1400 audit(1700484339.402:206): apparmor="DENIED" operation="open" profile="snap.microcloud.microcloud" name="/var/lib/snapd/hostfs/etc/ssl/certs/ca-certificates.crt" pid=5344 comm="microcloud" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

`
Even with above error , I am able to launch lxd containers over microcloud and run  workloads. I don't know whether this will affect any other use case under microcloud.

For the versions of the snaps that I am using....

`
lxd            5.19-31ff7b6            26096  latest/stable  canonical**  -
microceph      0+git.7b5672b           710    quincy/stable  canonical**  -
microcloud     1.1-04a1c49             737    latest/stable  canonical**  -
microovn       22.03.3+snap2d1a04de44  301    22.03/stable   canonical**  -

`

**Comment by masnax** [comment]
@simondeziel What is LXD's special handling around this? I've seen this error creep up a few times here and there so if there's something we can do about it I think we should.

**Comment by simondeziel** [comment]
@masnax https://github.com/canonical/lxd-pkg-snap/blob/latest-edge/snapcraft/commands/daemon.start#L243-L249

**Comment by masnax** [comment]
Hmm so this is based on LXD having its own internal `/etc`. I think that might be a bit overkill for MicroCloud at this point. I'll see what the snapd people have to say about this.

**Comment by masnax** [comment]
FWIW this seems to happen when MicroCloud reaches out to each remote LXD prior to clustering to fetch the available disks on the systems.

**Comment by tomponline** [comment]
Does microcloud need to access the system certs at all? Perhaps we should be configuring go not to use them?

**Comment by masnax** [comment]
> Does microcloud need to access the system certs at all? Perhaps we should be configuring go not to use them?

This is happening in `ConnectLXD` when setting up TLS. If `ConnectionArgs.TLSCA` is unset, then LXD will use the system config:
https://github.com/canonical/lxd/blob/f86e64427c65fd1d5061f9c45700f3618710e7d7/shared/network.go#L74-L79

**Comment by masnax** [comment]
So we could add some flag to `ConnectionArgs` to make it not set anything in this case.

**Comment by simondeziel** [comment]
Considering that LXD clusters can use certs from official root CAs (like Let's Encrypt and such) maybe we should keep the system certs?

**Comment by masnax** [comment]
Actually, looking at LXD's configuration, it seems to be reading the certs directly from `/var/lib/snapd/hostfs/etc/ssl`, but according to the link @simondeziel posted, it should just be able to access `/etc/ssl` directly, so maybe that's what we need here.

**Comment by masnax** [comment]
Indeed I'm not getting the error if I change LXD to read from `/etc/ssl` directly.

**Comment by masnax** [comment]
Should be fixed by https://github.com/canonical/lxd/pull/12541 once it's merged and MicroCloud is updated.

**Comment by roosterfish** [comment]
@masnax even though it's a LXD issue I would keep it here for tracking purposes and we can close it after MicroCloud got updated?
