### ISSUE TITLE
Can I use MC on a single computer?

### ISSUE THREAD

**Issue by hrstoyanov** [canonical/microcloud#229]
I know it requires 3 separate machines for production deployment, but I want to run it   on a single Ubuntu server with virtualization - is it possible?

**Comment by masnax** [comment]
If you mean you want a MicroCloud consisting of just 1 machine, then really what you need is LXD. MicroCloud just orchestrates LXD's built-in clustering of multiple systems alongside MicroOVN and MicroCeph. It's possible to use MicroCloud to set up a LXD cluster of least 2 systems, but you wouldn't get access to distributed networking or storage, which do require at least 3 systems.

If you mean you want a MicroCloud consisting of multiple VMs on a single system, then yes that's absolutely possible. Each VM should have a unique hostname and be on the same local network as the other VMs.

**Comment by hrstoyanov** [comment]
So, if understand this correctly: I set up 3+ VMS with LXD first in the same physical computer, and then I can deploy MicroCloud over these VMs and see all parts working (OVN, MicroCeph) in a completely virtualized way in my home lab?

Thank you for your answer, and btw, please enable Github discussions in for questions like this - it is much easier that asking people to register to other web site just for asking a question.

**Comment by tomponline** [comment]
Support issues are best posted here https://discourse.ubuntu.com/c/lxd/microcloud/145

**Comment by hrstoyanov** [comment]
@tomponline 
Imagine every project at Github forcing user to go and register to an external different web site, just so they can ask a question ...
