### ISSUE TITLE
Terraform provider

### ISSUE THREAD

**Issue by matifali** [canonical/microcloud#231]
Are there any plans for a terraform provider to manage infrastructure on a microcloud cluster?

**Comment by markylaing** [comment]
You can use the terraform provider for LXD to do this:
* https://github.com/terraform-lxd/terraform-provider-lxd
* https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docs

**Comment by roosterfish** [comment]
There is also a video from the MicroCloud launch event that showcases the usage of Terraform: https://www.youtube.com/live/Os0tAhlWTeg?si=dwyEpDG8s3tNBPWt
