### ISSUE TITLE
Feature Request: Ability to have Ceph using FDE

### ISSUE THREAD

**Issue by benoitjpnet** [canonical/microcloud#233]
I am not a fan of the fact that my data that is stored in Ceph is not encrypted.

Is this on the roadmap? Since MicroCeph already supports FDE, it could be implemented in MicroCloud when the cluster is bootstrapped.

Thank you very much!

**Comment by roosterfish** [comment]
FDE can be enabled now when using MicroCloud `2/stable`. See the release post https://discourse.ubuntu.com/t/microcloud-2-1-0-lts-has-been-released/49655.
