### ISSUE TITLE
Add support for single node MicroCloud

### ISSUE THREAD

**Issue by tomponline** [canonical/microcloud#282]

**Comment by masnax** [comment]
There's a lot of questions that will come up around this, particularly related to how we set up Ceph and OVN in MicroCloud today.

We require at least 3 systems to add ceph storage and ovn network to LXD today. 2-node clusters are limited to ZFS storage and a FAN network. This would mean that a 1-node MicroCloud would also only be limited to ZFS storage and a FAN network, so effectively `microcloud init` would be identical to `lxd init` with the cluster bootstrap options selected. 

We could potentially have a "no HA" option that allows setting up a 1 or 2 node MicroCloud with OVN and Ceph, though a user would have to be careful when growing the cluster to 3 members to undo all the configuration keys in ceph and ovn that allowed for the non-HA configuration.

**Comment by masnax** [comment]
Closed by #319
