### ISSUE TITLE
Cannot delete instances - image has watchers - not removing

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/microcloud#297]
Hello 

When trying to delete instances on Microcloud the instances fail to delete with the following error:

```
Error: Failed deleting instance "private-repo-lds-3" in project "REDACTED_PROJECT_NAME": Error deleting storage volume: Failed to delete volume: Failed to run: rbd --id admin --cluster ceph --pool lxd_remote rm virtual-machine_REDACTED_PROJECT_NAME_private-repo-lds-3.block: exit status 16 (2024-04-29T11:02:41.760+0000 7fe2f4898640 -1 librbd::image::PreRemoveRequest: 0x5563e888b7b0 check_image_watchers: image has watchers - not removing
Removing image: 0% complete...failed.
rbd: error: image still has watchers
This means the image is still open or the client using it crashed. Try again after closing/unmapping it or waiting 30s for the crashed client to timeout.)
```

The issue was produced by deploying a set of 14 VMs, with the following config: https://pastebin.canonical.com/p/DmfDtKc6cz/

The VMs were deployed on Friday, and left over the weekend. When destroying the VMs then failed with the above error

# Workaround
1. `sudo ps aux | grep qemu`
2. Identify the process for your VMs
3. `sudo kill ${PID}`

Peter

**Comment by tomponline** [comment]
VMs were found to have crashed, killing qemu processes released the rbd volumes to allow deletion.

**Comment by VariableDeclared** [comment]
The steps to reproduce this:

1. Create VMs as described
2. Add a new network VLAN to bond on which LXD is running its services via netplan, e.g. vlan with ID 55
3. Apply VLAN changes
4. Allow cluster to settle
5. Attempt removal

Thank you
Peter

**Comment by roosterfish** [comment]
@VariableDeclared is this still an issue?

**Comment by VariableDeclared** [comment]
I think we can close this, thanks for checking in @roosterfish :)
