### ISSUE TITLE
Add support for local storage

### ISSUE THREAD

**Issue by stgraber** [canonical/microcloud#30]
When initializing a MicroCloud, local storage should be offered prior to setting up remote storage.

The updated `microcloud init` process should therefore be:
 - Bootstrap
 - Detect and join other servers
 - Ask whether the user wants to setup local storage, if yes
   - Check that we have at least one available disk per server
   - Ask the user to select exactly one disk per server
 - Ask whether the user wants to setup remote storage, if yes
   - Check that we have at least three disks spread across at least three servers
   - Ask the user to select what disks to include into Ceph
 - If local storage was chosen, use it for the default profile, otherwise use remote (if was setup)

**Comment by masnax** [comment]
Closed by #37
