### ISSUE TITLE
Allow removing machines from a MicroCloud

### ISSUE THREAD

**Issue by stgraber** [canonical/microcloud#33]
We should introduce a `microcloud add` and `microcloud remove` command to add/remove servers to the cluster.
The `microcloud add` would be a scriptable version of what we do through `microcloud init`.

`microcloud remove` is the trickier one as it will have to validate that:
 - LXD is empty on the system
 - Ceph isn't dependent on that server (can operate without it)

And if that's the case, then perform the removal from LXD, Ceph and OVN before removing it from MicroCloud.
The expectation is that the server will then go back to a pristine stage and so should multicast over MDNS again and be possible to add it back to the MicroCloud.

**Comment by roosterfish** [comment]
Closing this one as a duplicate in favor of https://github.com/canonical/microcloud/issues/160.
