### ISSUE TITLE
docs: one-off configuration of microcloud host instead of using persistent config in netplan

### ISSUE THREAD

**Issue by nobuto-m** [canonical/microcloud#360]
*Please describe the question or issue you're facing with "Get started with MicroCloud".*

https://canonical-microcloud.readthedocs-hosted.com/en/latest/tutorial/get_started/#install-microcloud-on-each-vm
> Configure the network interface connected to microbr0 to not accept any IP addresses (because MicroCloud requires a network interface that doesn’t have an IP address assigned):
> 
> echo 0 > /proc/sys/net/ipv6/conf/enp6s0/accept_ra
>  
> Bring the network interface up:
> 
> ip link set enp6s0 up

I don't think those two operations can survive after a host reboot. i.e. the cluster host gets non functional as soon as there is a need of a reboot of the host such as kernel updates.

---
*Reported from: https://canonical-microcloud.readthedocs-hosted.com/en/latest/tutorial/get_started/*

**Comment by roosterfish** [comment]
Please consider one of the first sentences of this tutorial:

> This tutorial guides you through installing MicroCloud in a confined environment and then starting some instances to see what you can do with MicroCloud. It uses virtual machines in LXD, so you don’t need any extra hardware to follow the tutorial.

It's not meant for production scenarios and should only provide you with a sandbox environment to try out MicroCloud.

Having said this, do you currently experience issues when rebooting any of the nodes? If the `echo 0 > /proc/sys/net/ipv6/conf/enp6s0/accept_ra` is of concert I suspect we can also configure the `microbr0` interface in a way to not hand out IPv6 addresses.

**Comment by nobuto-m** [comment]
> It's not meant for production scenarios and should only provide you with a sandbox environment to try out MicroCloud.

I understand this point. Still we can instruct people with a better way wherever possible.

A drop-in file for the interface can be used to mark the interface up and disable IPv6 etc.
https://netplan.readthedocs.io/en/latest/netplan-tutorial/#editing-netplan-yaml-files-to-disable-ipv6
