### ISSUE TITLE
Make sure we pull the correct version of the documentation

### ISSUE THREAD

**Issue by ru-fu** [canonical/microcloud#374]
If https://github.com/canonical/microcloud/pull/372 is merged, we'll pull in specific versions of the LXD/MicroCeph/MicroOVN documentation.
These versions can be specified in the Makefile.

They must be updated before the release to match the supported versions. Ideally, this should be done automatically based on our compatibility matrix.

**Comment by roosterfish** [comment]
Can be closed as those version were pinned in https://github.com/canonical/microcloud/pull/490.
