### ISSUE TITLE
No suggestion to configure an uplink for OVN

### ISSUE THREAD

**Issue by nobuto-m** [canonical/microcloud#89]
Follow-up of #87

microcloud  0+git.136aeb1

Even if one NIC is prepared as unconfigured to be consumed by OVN, microcloud skips the OVN step with `No dedicated uplink interfaces detected, skipping distributed networking`. The expectation is to guide users through to configure OVN with an uplink.

```
ubuntu@mc-1:~$ ip -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128 
enp1s0           UP             192.168.122.172/24 metric 100 fe80::5054:ff:fe56:3c7d/64 
enp7s0           DOWN           
```

^^^ `enp7s0` is unconfigured at that point.

```
ubuntu@mc-1:~$ sudo microcloud init
Using address "192.168.122.172" for MicroCloud
Limit search for other MicroCloud servers to 192.168.122.172/24? (yes/no) [default=yes]: 
Scanning for eligible servers...

 Selected "mc-2" at "192.168.122.105"
 Selected "mc-3" at "192.168.122.219"

Would you like to setup local storage? (yes/no) [default=yes]: 
Select exactly one disk from each cluster member:

 Using "/dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001" on "mc-3" for local storage pool
 Using "/dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001" on "mc-1" for local storage pool
 Using "/dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001" on "mc-2" for local storage pool

Would you like to setup distributed storage? (yes/no) [default=yes]: 
Select from the available unpartitioned disks:

Select which disks to wipe:

 Using 1 disk(s) on "mc-1" for remote storage pool
 Using 1 disk(s) on "mc-2" for remote storage pool
 Using 1 disk(s) on "mc-3" for remote storage pool

No dedicated uplink interfaces detected, skipping distributed networking
Initializing a new cluster
 Local MicroCloud is ready
 Local LXD is ready
 Local MicroOVN is ready
 Local MicroCeph is ready
Awaiting cluster formation...
 Peer "mc-3" has joined the cluster
 Peer "mc-2" has joined the cluster
Cluster initialization is complete
MicroCloud is ready
```

```
$ lxc network list
+---------+----------+---------+------+------+-------------+---------+---------+
|  NAME   |   TYPE   | MANAGED | IPV4 | IPV6 | DESCRIPTION | USED BY |  STATE  |
+---------+----------+---------+------+------+-------------+---------+---------+
| enp1s0  | physical | NO      |      |      |             | 0       |         |
+---------+----------+---------+------+------+-------------+---------+---------+
| enp7s0  | physical | NO      |      |      |             | 0       |         |
+---------+----------+---------+------+------+-------------+---------+---------+
| lxdfan0 | bridge   | YES     |      |      |             | 1       | CREATED |
+---------+----------+---------+------+------+-------------+---------+---------+
```

```
$ lxc profile show default
config: {}
description: ""
devices:
  eth0:
    name: eth0
    network: lxdfan0
    type: nic
  root:
    path: /
    pool: remote
    type: disk
name: default
used_by: []
```

**Comment by stgraber** [comment]
We'll be providing a lot more details about what's expected once @ru-fu is back and we can spend some time on documentation.

In your case, the logic is correct, you don't have an interface that's usable because your external interface is set to DOWN.
If we were to tell OpenVswitch to consume it, it would not work.

**Comment by stgraber** [comment]
For an uplink NIC to be considered at all, it needs to:
 - Be a physical NIC, a VLAN off a physical NIC or a bridge device
 - Be currently up
 - Not be used by a managed network in LXD
 - Not have any global IP addresses on it (link-local is tolerated)
 - Be a proper L2 device with broadcast support (no tunnel or similar devices)

Additionally, you should consider that OVN uses Geneve tunnels and so will typically have a MTU overhead of 58 bytes.
As a result, if you want your virtual networks to get a traditional 1500 MTU, you're going to need your uplink to be at least 1558 (though I'd personally round that up to 1600 for good measure).

**Comment by nobuto-m** [comment]
> In your case, the logic is correct, you don't have an interface that's usable because your external interface is set to DOWN.
> If we were to tell OpenVswitch to consume it, it would not work.

That's fair. 

Yes, it may be a part of documentation upcoming. But in an ideal world, it would be nice if microcloud lists interfaces even with DOWN status and suggest to configure it by dropping a netplan override file on behalf of the user at the following step.

```
Configure distributed networking? (yes/no) [default=yes]: 
Space to select; Enter to confirm; Type to filter results.
Up/Down to move; Right to select all; Left to select none.
       +----------+--------+----------+
       | LOCATION | IFACE  |   TYPE   |
       +----------+--------+----------+
> [ ]  | mc-1     | enp7s0 | physical |
  [ ]  | mc-2     | enp7s0 | physical |
  [ ]  | mc-3     | enp7s0 | physical |
       +----------+--------+----------+
```

**Comment by stgraber** [comment]
We're a strictly confined snap, we can't see or alter global system configuration.

**Comment by nobuto-m** [comment]
Hmm indeed. Not sure if "network-setup-control" is helpful or not for it.
https://github.com/snapcore/snapd/blob/9f924e96d657f0239792dc02690d7ec539f0a2a1/interfaces/builtin/network_setup_control.go

**Comment by tomponline** [comment]
You can use `link-local: []` to disable IPv6 link-local addresses so the uplink interface isn't considered in use.

**Comment by dnebing** [comment]
So the ipv4 configuration won't matter, only the ipv6?

**Comment by tomponline** [comment]
ipv4 matters too, but isnt automatic unless you have dhcp enabled
